name: WeightOfItems
version: '1.0'
main: me.nyarikori.weightOfItems.WeightOfItems
api-version: '1.20'
load: POSTWORLD
authors: [ NyariKori ]
website: https://github.com/NyariKori
softdepend:
  - PlaceholderAPI